In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

In [29]:
data = pd.read_csv("df_imputed.csv")
data.drop(data.columns[0], axis=1, inplace=True)
data

id  aniongap  bicarbonate   bun  calcium  chloride  creatinine  \
0      20001305.0      15.0         23.0  47.0     11.4     108.0         0.8   
1      20001305.0      13.0         25.0  48.0     10.8     107.0         0.9   
2      20001305.0      13.0         24.0  50.0     10.8     108.0         0.9   
3      20001361.0      14.0         22.0  28.0      6.3     107.0         2.5   
4      20001361.0      15.0         20.0  32.0      6.5     108.0         2.5   
...           ...       ...          ...   ...      ...       ...         ...   
93599  29999498.0      20.0         22.0  13.0     11.2     100.0         1.2   
93600  29999498.0      15.0         21.0  13.0     10.1     103.0         1.2   
93601  29999625.0      17.0         21.0  14.0      8.5     104.0         1.2   
93602  29999625.0      15.0         24.0  21.0      8.6     110.0         1.6   
93603  29999625.0      15.0         24.0  21.0      8.6     110.0         1.6   

       glucose  sodium  potassium  ...  admission_type_URGENT  \
0        154.0   142.0        4.3  ...                      0   
1        149.0   140.0        4.7  ...                      0   
2        131.0   141.0        4.1  ...                      0   
3        161.0   137.0        5.8  ...                      0   
4        124.0   137.0        5.7  ...                      0   
...        ...     ...        ...  ...                    ...   
93599     76.0   137.0        4.6  ...                      0   
93600    102.0   135.0        4.2  ...                      0   
93601    109.0   142.0        4.6  ...                      0   
93602    122.0   149.0        4.1  ...                      0   
93603    122.0   148.0        4.1  ...                      0   

       first_careunit_Cardiac Vascular Intensive Care Unit (CVICU)  \
0                                                      0             
1                                                      0             
2                                                      0             
3                                                      0             
4                                                      0             
...                                                  ...             
93599                                                  0             
93600                                                  0             
93601                                                  0             
93602                                                  0             
93603                                                  0             

       first_careunit_Coronary Care Unit (CCU)  \
0                                            0   
1                                            0   
2                                            0   
3                                            0   
4                                            0   
...                                        ...   
93599                                        0   
93600                                        0   
93601                                        0   
93602                                        0   
93603                                        0   

       first_careunit_Medical Intensive Care Unit (MICU)  \
0                                                      0   
1                                                      0   
2                                                      0   
3                                                      0   
4                                                      0   
...                                                  ...   
93599                                                  0   
93600                                                  0   
93601                                                  0   
93602                                                  0   
93603                                                  0   

       first_careunit_Medical/Surgical Intensive Care Unit (MICU/SICU)  \
0                       

In [30]:
y=data['icu_death']
data.drop('icu_death', axis=1, inplace=True)
X = data
X

id  aniongap  bicarbonate   bun  calcium  chloride  creatinine  \
0      20001305.0      15.0         23.0  47.0     11.4     108.0         0.8   
1      20001305.0      13.0         25.0  48.0     10.8     107.0         0.9   
2      20001305.0      13.0         24.0  50.0     10.8     108.0         0.9   
3      20001361.0      14.0         22.0  28.0      6.3     107.0         2.5   
4      20001361.0      15.0         20.0  32.0      6.5     108.0         2.5   
...           ...       ...          ...   ...      ...       ...         ...   
93599  29999498.0      20.0         22.0  13.0     11.2     100.0         1.2   
93600  29999498.0      15.0         21.0  13.0     10.1     103.0         1.2   
93601  29999625.0      17.0         21.0  14.0      8.5     104.0         1.2   
93602  29999625.0      15.0         24.0  21.0      8.6     110.0         1.6   
93603  29999625.0      15.0         24.0  21.0      8.6     110.0         1.6   

       glucose  sodium  potassium  ...  admission_type_URGENT  \
0        154.0   142.0        4.3  ...                      0   
1        149.0   140.0        4.7  ...                      0   
2        131.0   141.0        4.1  ...                      0   
3        161.0   137.0        5.8  ...                      0   
4        124.0   137.0        5.7  ...                      0   
...        ...     ...        ...  ...                    ...   
93599     76.0   137.0        4.6  ...                      0   
93600    102.0   135.0        4.2  ...                      0   
93601    109.0   142.0        4.6  ...                      0   
93602    122.0   149.0        4.1  ...                      0   
93603    122.0   148.0        4.1  ...                      0   

       first_careunit_Cardiac Vascular Intensive Care Unit (CVICU)  \
0                                                      0             
1                                                      0             
2                                                      0             
3                                                      0             
4                                                      0             
...                                                  ...             
93599                                                  0             
93600                                                  0             
93601                                                  0             
93602                                                  0             
93603                                                  0             

       first_careunit_Coronary Care Unit (CCU)  \
0                                            0   
1                                            0   
2                                            0   
3                                            0   
4                                            0   
...                                        ...   
93599                                        0   
93600                                        0   
93601                                        0   
93602                                        0   
93603                                        0   

       first_careunit_Medical Intensive Care Unit (MICU)  \
0                                                      0   
1                                                      0   
2                                                      0   
3                                                      0   
4                                                      0   
...                                                  ...   
93599                                                  0   
93600                                                  0   
93601                                                  0   
93602                                                  0   
93603                                                  0   

       first_careunit_Medical/Surgical Intensive Care Unit (MICU/SICU)  \
0                       

In [16]:
y

0        1.0
1        1.0
2        1.0
3        0.0
4        0.0
        ... 
93599    0.0
93600    0.0
93601    0.0
93602    0.0
93603    0.0
Name: icu_death, Length: 93604, dtype: float64

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [54]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [35]:

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

predictions = model.predict(X_test)
print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))


              precision    recall  f1-score   support

         0.0       0.97      1.00      0.98     16218
         1.0       1.00      0.78      0.88      2503

    accuracy                           0.97     18721
   macro avg       0.98      0.89      0.93     18721
weighted avg       0.97      0.97      0.97     18721

[[16218     0]
 [  544  1959]]


In [33]:
from sklearn.metrics import roc_auc_score
auroc = roc_auc_score(y_test, predictions)
print(f"Multi-class AUROC (One-vs-Rest): {auroc}")

Multi-class AUROC (One-vs-Rest): 0.8913304035157811


In [36]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

predictions = model.predict(X_test)
print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))
auroc = roc_auc_score(y_test, predictions)
print(f"Multi-class AUROC (One-vs-Rest): {auroc}")

              precision    recall  f1-score   support

         0.0       0.98      0.98      0.98     16218
         1.0       0.85      0.84      0.84      2503

    accuracy                           0.96     18721
   macro avg       0.91      0.91      0.91     18721
weighted avg       0.96      0.96      0.96     18721

[[15844   374]
 [  406  2097]]
Multi-class AUROC (One-vs-Rest): 0.9073669248892942


In [38]:
from xgboost import XGBClassifier

# Initialize the XGBoost classifier
model = XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='mlogloss')

# Fit the model to the training data
model.fit(X_train, y_train)

# Model evaluation
predictions = model.predict(X_test)

# Print the classification report and confusion matrix
print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))
auroc = roc_auc_score(y_test, predictions)
print(f"Multi-class AUROC (One-vs-Rest): {auroc}")

              precision    recall  f1-score   support

         0.0       0.96      1.00      0.98     16218
         1.0       0.97      0.75      0.84      2503

    accuracy                           0.96     18721
   macro avg       0.97      0.87      0.91     18721
weighted avg       0.96      0.96      0.96     18721

[[16158    60]
 [  636  1867]]
Multi-class AUROC (One-vs-Rest): 0.8711026605291556


In [51]:
# Initialize logistic regression model with class weights balanced
model = LogisticRegression(class_weight='balanced', random_state=42)

# Fit the model on the balanced training data
model.fit(X_train, y_train)

# Predict on the test data
predictions = model.predict(X_test_scaled)

# Print the classification report and confusion matrix
print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))
auroc = roc_auc_score(y_test, predictions)
print(f"Multi-class AUROC (One-vs-Rest): {auroc}")

              precision    recall  f1-score   support

         0.0       0.91      0.51      0.65     16218
         1.0       0.18      0.69      0.28      2503

    accuracy                           0.53     18721
   macro avg       0.55      0.60      0.47     18721
weighted avg       0.82      0.53      0.60     18721

[[8248 7970]
 [ 767 1736]]
Multi-class AUROC (One-vs-Rest): 0.6010692213122771


D:\anaconda3\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  "X does not have valid feature names, but"
